/* Generated by opensource COBOL 4J 1.1.12 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;
import java.lang.NullPointerException;
import java.lang.IndexOutOfBoundsException;

public class prog1 implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return prog1_(0, argStorages);
  }

  @Override
  public void cancel() {
    prog1_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int prog1_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("prog1");

      b_RETURN_CODE.set((int)0);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      CobolStopRunException.dummy();
      CobolGoBackException.dummy();
      /* Entry dispatch */
      execEntry(l_prog1);

    } catch(CobolGoBackException e) {
      return e.getReturnCode();
    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_prog1]);
      }
    },
    /* Entry prog1 */
    new CobolControl(l_prog1, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__label_1]);
      }
    },
    /* label-1 */
    new CobolControl(l_MAIN_SECTION__label_1, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:7: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_1_label);
        }
        /* prog1.cbl:8: GO TO */
        {
          if(true) return Optional.of(contList[l_MAIN_SECTION__label_5          ]);

        }

        return Optional.of(contList[l_MAIN_SECTION__label_2]);
      }
    },
    /* label-2 */
    new CobolControl(l_MAIN_SECTION__label_2, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:11: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_2_label);
        }

        return Optional.of(contList[l_MAIN_SECTION__label_3]);
      }
    },
    /* label-3 */
    new CobolControl(l_MAIN_SECTION__label_3, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:14: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_3_label);
        }

        return Optional.of(contList[l_MAIN_SECTION__label_4]);
      }
    },
    /* label-4 */
    new CobolControl(l_MAIN_SECTION__label_4, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:17: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_4_label);
        }

        return Optional.of(contList[l_MAIN_SECTION__label_5]);
      }
    },
    /* label-5 */
    new CobolControl(l_MAIN_SECTION__label_5, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:20: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_5_label);
        }
        /* prog1.cbl:22: PERFORM */
        /* PERFORM label-2 THRU label-4 */
        CobolControl.performThrough(contList, 
l_MAIN_SECTION__label_2, l_MAIN_SECTION__label_4).run();
        /* prog1.cbl:24: GO TO */
        {
          if(true) return Optional.of(contList[l_end_prog          ]);

        }

        return Optional.of(contList[l_MAIN_SECTION__dummy_label]);
      }
    },
    /* dummy-label */
    new CobolControl(l_MAIN_SECTION__dummy_label, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:27: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_6_this);
        }

        return Optional.of(contList[l_end_prog]);
      }
    },
    /* end-prog SECTION */
    new CobolControl(l_end_prog, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_end_prog_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* end-prog_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_end_prog_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:30: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_7_end);
        }

        return Optional.of(contList[l_end_prog__end_prog_1]);
      }
    },
    /* end-prog-1 */
    new CobolControl(l_end_prog__end_prog_1, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:32: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_8_end);
        }

        return Optional.of(contList[l_end_prog__end_prog_2]);
      }
    },
    /* end-prog-2 */
    new CobolControl(l_end_prog__end_prog_2, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:34: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_9_end);
        }

        return Optional.of(contList[l_stop_run]);
      }
    },
    /* stop-run SECTION */
    new CobolControl(l_stop_run, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_stop_run_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* stop-run_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_stop_run_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* prog1.cbl:37: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_10_stop);
        }
        /* prog1.cbl:38: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new prog1().prog1_(0);
    CobolStopRunException.stopRun();
  }

  public prog1()
  {
    init();
  }

  public void init() 
  {
    try {
      /* Data storage */

      cob_unifunc = null;

      /* PROGRAM-ID : prog1 */
      b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */

      /* End of data storage */


      initAttr();

      /* Constants */

      c_1_label	= CobolFieldFactory.makeCobolField(str_0_label, a_1);
      c_2_label	= CobolFieldFactory.makeCobolField(str_1_label, a_1);
      c_3_label	= CobolFieldFactory.makeCobolField(str_2_label, a_1);
      c_4_label	= CobolFieldFactory.makeCobolField(str_3_label, a_1);
      c_5_label	= CobolFieldFactory.makeCobolField(str_4_label, a_1);
      c_6_this	= CobolFieldFactory.makeCobolField(str_5_this, a_1);
      c_7_end	= CobolFieldFactory.makeCobolField(str_6_end, a_1);
      c_8_end	= CobolFieldFactory.makeCobolField(str_7_end, a_1);
      c_9_end	= CobolFieldFactory.makeCobolField(str_8_end, a_1);
      c_10_stop	= CobolFieldFactory.makeCobolField(str_9_stop, a_1);

    } catch(NullPointerException e) {
      System.out.println("Error - NullpointerException");
    } catch(IndexOutOfBoundsException e) {
      System.out.println("Error - IndexOutOfBoundsException");
    }
  }

  private void initAttr() {
    /* Attributes */

    a_1 = new CobolFieldAttribute (33, 0, 0, 0, null);

  }

  /* Data storage */

  /* PROGRAM-ID : prog1 */
  private CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */

  /* End of data storage */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_10_stop;
  private AbstractCobolField c_9_end;
  private AbstractCobolField c_8_end;
  private AbstractCobolField c_7_end;
  private AbstractCobolField c_6_this;
  private AbstractCobolField c_5_label;
  private AbstractCobolField c_4_label;
  private AbstractCobolField c_3_label;
  private AbstractCobolField c_2_label;
  private AbstractCobolField c_1_label;

  /* Attributes */

  private CobolFieldAttribute a_1;



  /* String literals */
  public static final byte[] str_9_stop = CobolUtil.stringToBytes("stop-run");
  public static final byte[] str_8_end = CobolUtil.stringToBytes("end-2");
  public static final byte[] str_7_end = CobolUtil.stringToBytes("end-1");
  public static final byte[] str_6_end = CobolUtil.stringToBytes("end-prog section");
  public static final byte[] str_5_this = CobolUtil.stringToBytes("this is not displayed");
  public static final byte[] str_4_label = CobolUtil.stringToBytes("label-5");
  public static final byte[] str_3_label = CobolUtil.stringToBytes("label-4");
  public static final byte[] str_2_label = CobolUtil.stringToBytes("label-3");
  public static final byte[] str_1_label = CobolUtil.stringToBytes("label-2");
  public static final byte[] str_0_label = CobolUtil.stringToBytes("label-1");

  /* Sections and Labels */
  private final static int l_prog1 = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__label_1 = 3;
  private final static int l_MAIN_SECTION__label_2 = 4;
  private final static int l_MAIN_SECTION__label_3 = 5;
  private final static int l_MAIN_SECTION__label_4 = 6;
  private final static int l_MAIN_SECTION__label_5 = 7;
  private final static int l_MAIN_SECTION__dummy_label = 8;
  private final static int l_end_prog = 9;
  private final static int l_end_prog_SECTION__DEFAULT_PARAGRAPH = 10;
  private final static int l_end_prog__end_prog_1 = 11;
  private final static int l_end_prog__end_prog_2 = 12;
  private final static int l_stop_run = 13;
  private final static int l_stop_run_SECTION__DEFAULT_PARAGRAPH = 14;
  private final static int l_Default_Error_Handler = 15;

}
