name: msbuild

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ./win/

    - name: Build
      run: msbuild /p:Configuration=Release /p:AdditionalIncludePaths=./:./cobj/:./win:./lib win/opensourcecobol4j.sln

    - name: Execute cobj
      run: |
        cd win/x64/Release
        ./cobj.exe --version

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.32"
        distribution: strawberry
    
    - name: Preparation of test
      run : |
        cd win
        .\make-install.ps1
        $env:CLASSPATH="C:\opensourcecobol4j\bin\libcobj.jar"
        $env:PATH+=";C:\opensourcecobol4j\bin\;C:\opensourcecobol4j\config\"

