name: MSBuild

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ./win/

    - name: Build
      run: msbuild /p:AdditionalIncludePaths=./:./cobj/:./win:./lib win/opensourcecobol4j.sln

    - name: Execute cobj
      run: |
        cd win/x64/Debug
        ./cobj.exe --version

    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.32"
        distribution: strawberry
    
    - name: Run test
      run : |
        cd win
        ./make-test.ps1
