name: Scan by Sonar
on:
  workflow_call:
env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        checks: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        LC_ALL: "ja_JP.UTF-8"

